version: '3.4'

services:
  webapi-tic-tac-toe:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RedisConnection: redisdb:6379
    ports:
      - 5000:80
    depends_on:
      - redisdb
    restart: always

  redisdb:
    ports:
      - 6379:6379
    volumes:
      - redisdb_data:/data
    restart: always

volumes:
  redisdb_data: